-- Reset the icons as I dont like them
local kind = {
    File =  "",
    Module = "",
    Namespace = "",
    Package = "",
    Class = "",
    Method = "",
    Property = "",
    Field = "",
    Constructor = "",
    Enum = "",
    Interface = "",
    Function = "",
    Variable = "",
    Constant = "",
    String = "",
    Number = "",
    Boolean = "",
    Array = "",
    Object = "",
    Key = "",
    Null = "",
    EnumMember = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
    TypeAlias = "",
    Parameter = "",
    StaticMethod = "",
    Macro = "",
    Text = "",
    Snippet = "",
    Folder = "",
    Unit = "",
    Value = "",
}

require'lspsaga'.setup {
    -- diagnostic_header_icon = '»',
    -- error, warn, info, hint
    symbol_in_winbar = { separator = '»' },
    diagnostic_header = { '•e', '•w', '•i', '•h', },
    code_action_icon = '?',
    code_action_lightbulb = {
        enable = true,
        sign = true,
        sign_priority = 20,
        virtual_text = true,
    },
    code_action_keys = {quit = '<esc>', exec = '<CR>'},
    finder_icons = {
        def = '•d',
        ref = '•r',
        link = '•l',
    },
    finder_action_keys = {
        open = 'o',
        vsplit = 's',
        split = 'i',
        quit = '<esc>',
        scroll_down = '<C-n>',
        scroll_up = '<C-p>'
    },
    ui = { kind = kind }
}
