[tools]
bat = "latest"  # less
jless = "latest"  # less with jq
hwatch = "latest"  # watch
bottom = "latest"  # top
"github:dalance/amber" = "latest"  # text replace
fd = "latest"  # find
yj = "latest"  # json/yaml converter
