{...}: {
  services.nix-daemon.enable = true;
  nix.extraOptions = ''
    extra-platforms = x86_64-darwin aarch64-darwin
    extra-nix-path = nixpkgs=flake:nixpkgs
  '';
  nix.settings.extra-trusted-users = ["bruno.tavares"];

  # # # Generated by https://github.com/DeterminateSystems/nix-installer.
  # # See `/nix/nix-installer --version` for the version details.

  # build-users-group = nixbld
  # experimental-features = nix-command flakes repl-flake
  # bash-prompt-prefix = (nix:$name)\040
  # max-jobs = auto
  # extra-nix-path = nixpkgs=flake:nixpkgs
  # upgrade-nix-store-path-url = https://install.determinate.systems/nix-upgrade/stable/universal
  # use-case-hack = false
  # trusted-users = bruno.tavares
}
