# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="fringe"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(battery heroku bundler git_ps1 no_git_ps1 aliases)

source $ZSH/oh-my-zsh.sh

if [[ -f $HOME/.host_specific ]] then
 source $HOME/.host_specific
fi

alias tw='t timeline -r'
rtw () {
 t timeline -l | awk "FNR==$1{ print \$1}" | xargs t retweet
}
genpasswd() {
  grep "^[^'A-Z]\{3,7\}$" /usr/share/dict/words | shuf -n4 | tr '\n' ' ' | sed 's/\b\(.\)/\u\1/g' | sed 's/ //g'
}

camelize() {
    read phrases
    echo -e "$phrases" | perl -pe 's/\b(.)/\u\1/g' | sed 's/ //g'
}

# Customize to your needs...
#export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl

#Git ps1
GIT_PS1_SHOWDIRTYSTATE=true
#GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM=true

alias eufori="cd /repos/eufori;clear"
alias repos="cd /repos"

alias be="bundle exec "
alias minecraft="java -Xmx1660M -Xms1660M -jar ~/minecraft.jar"

function say { mplayer -really-quiet "http://translate.google.com/translate_tts?tl=en&q=$1"; }

#include RVM if it exist    
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

if [[ "$TERM" == "xterm" ]]; then
  # No it isn't, it's gnome-terminal
  export TERM=xterm-256color
fi

export PATH="$HOME/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
#Seahorse
#export $(gnome-keyring-daemon --start --components ssh)
